Photon counting
roman-corgi/corgidrp pull request #277
Opened 2024-12-26 18:04 UTC by kjl0025

## Describe your changes
Added a step function for photon counting frames.  Also addressed some other minor issues. (This is the same as the PR I had into the main branch.)

## Type of change

Please delete options that are not relevant (and this line).

- New feature (non-breaking change which adds functionality)

## Reference any relevant issues (don't forget the #)
#2 , #200 , #244 

## Checklist before requesting a review
- [X] I have linted my code
- [X] I have verified that all unit tests pass in a clean environment and added new unit tests, as needed
- [X] I have verified that all docstrings are properly formatted and added new documentation, as needed

2025-01-08 18:56 UTC, semaphoreP commented
@kjl0025 can you finish filling out the DRP Test Definition row with your test description. It'll actually be helpful for my review to be able to read through the tests at a high level. (Rather than waiting to fill it out after PR review).

2025-01-09 14:53 UTC, kjl0025 commented
Sure, just finished doing that.

2025-01-13 16:00 UTC, semaphoreP commented on tests/e2e_tests/photon_count_e2e.py
> +    this_caldb.remove_entry(new_nonlinearity)
we should also remove the PC Dark from the caldb as well.

2025-01-13 16:14 UTC, semaphoreP commented on tests/test_photon_counting.py
> +    dataset_err.all_data = dataset_err.all_data.astype(float)*7 - 20000.
I think if you do `dataset_err.all_data[:] = dataset_err.all_data.astype(float)*7 - 20000.` with the `[:]` (and equivalent for line 38), then you don't need lines 33-36.

2025-01-13 16:20 UTC, semaphoreP commented on tests/test_photon_counting.py
> +    '''Test that a pixel that is masked heavily (reducing the number of usable frames for that pixel) has a bigger err than the average pixel.
The docstring is a bit hard to read. Can we put each thing that is being tested in a new line?

We should also mention that we test the dark subtraction from illuminated frames gives the expected value.

2025-01-14 19:55 UTC, kjl0025 commented on corgidrp/recipe_templates/l1_to_l2b_pc_dark.json
> +            "name": "get_pc_mean"
Okay, sounds good.  I'll make a flag input, and I'll make it raise an exception if the flag value is incompatible with the VISTYPE.

2025-01-14 20:32 UTC, kjl0025 commented on tests/e2e_tests/photon_count_e2e.py
> +    walker.walk_corgidrp(l1_data_dark_filelist, '', output_dir, template="l1_to_l2b_pc_dark.json")
I think it would be good for the user to have the freedom to override and run either the PC or analog pipeline, but the walker could be informed by the 'ISPC' header listed here (https://collaboration.ipac.caltech.edu/display/romancoronagraph/L1+image+headers+SSC+release+3.2)?

2025-01-17 17:17 UTC, kjl0025 commented on tests/e2e_tests/photon_count_e2e.py
> +    dark_entry = data.Dark(pc_dark_file)
It does add it in.  You're right, I don't actually need to add it in.  I just copied lines from a previous formatting.

2025-01-23 21:26 UTC, kjl0025 commented on tests/test_photon_counting.py
> +    dataset_err.all_data = dataset_err.all_data.astype(float)*7 - 20000.
I had tried that kind of approach at first, but it didn't work.  The `data` for each frame and `all_data` aren't linked in such a way to update if one of them changes.

2025-01-23 22:00 UTC, kjl0025 commented
Alright, I think I've addressed all your comments.  Should be good to go.

2025-01-27 12:34 UTC, semaphoreP approved these changes
Hi Kevin, two small comments remaining (weird that only one got attached to this comment.. there's another one above). I also need to run the e2e tests myself to make sure they run now, but I will assume you fixed those issues.

2025-01-27 12:34 UTC, semaphoreP commented on corgidrp/data.py
> +            self.ext_hdr['RN'] = ''
should we be initializing them to 0? feels awkward to initalize to a different data type

2025-01-27 14:47 UTC, kjl0025 commented on tests/e2e_tests/photon_count_e2e.py
> +    for i in range(len(post_caldb._db['Type'])):
Ah, true.  It does update it for me, but I do agree that your suggestion is better since `remove_entry` does more than just `drop` (and it does it by finding the corresponding filename and not just by type).

2025-01-27 14:52 UTC, kjl0025 commented on tests/e2e_tests/photon_count_e2e.py
> +    walker.walk_corgidrp(l1_data_dark_filelist, '', output_dir, template="l1_to_l2b_pc_dark.json")
I think the way to do the trigger would be to have the walker choose the path based on the 'ISPC' header listed here (https://collaboration.ipac.caltech.edu/display/romancoronagraph/L1+image+headers+SSC+release+3.2).  I can edit the walker accordingly on this PR if you'd like?

2025-01-27 14:54 UTC, kjl0025 commented on corgidrp/data.py
> +            self.ext_hdr['RN'] = ''
I chose to do a different data type so that we would know for sure if the cal files were legitimate when an error is thrown further down the line.  In other words, I wouldn't want a fake value to be mistakenly used as the real calibrated value when it is called for in a step function.

2025-01-27 15:50 UTC, semaphoreP commented on tests/e2e_tests/photon_count_e2e.py
> +    walker.walk_corgidrp(l1_data_dark_filelist, '', output_dir, template="l1_to_l2b_pc_dark.json")
Yes, that would be great if you can add it. that way, it doesn't force us to manually figure out the PC recipes each time (PC Dark, and PC L1 -> L2b)

2025-01-27 15:51 UTC, semaphoreP commented on corgidrp/data.py
> +            self.ext_hdr['RN'] = ''
ok. as long as it doesn't break things that use this attribute.

2025-01-30 09:03 UTC, semaphoreP requested changes
Just ran the e2e tests and the input argument naming needs to be fixed in order for the batch pytest framework to run the e2e tests. 

Can you also fix the conflict with mock?

2025-01-30 09:03 UTC, semaphoreP commented on tests/e2e_tests/photon_count_e2e.py
> +def test_expected_results_e2e(tvacdata_dir, file_dir):
The arguments need to be named `tvacdata_path, e2eoutput_path` exactly for the pytest framework to run correctly. Can you rename these two argument variables?

2025-02-10 16:15 UTC, kjl0025 commented
Should be good to go now.

2025-02-10 16:58 UTC, kjl0025 commented
Oops, not yet.  Fixing

2025-02-12 23:48 UTC, semaphoreP reviewed
Hi Kevin, just a few small changes in the code, to conform to some python best practices and hopefully avoid bugs in future development. 

Additionally, it seems like header keywords for CMDGAIN and KGAIN have changed. Can you make a new issue to track that we should update these header keywords? I would strongly advocate not doing it in this PR so we can wrap up the last few things and merge!

2025-02-12 23:48 UTC, semaphoreP commented on corgidrp/calibrate_kgain.py
> +                    verbose=False, detector_regions=None, kgain_params=kgain_params_default):
the python "best practices" on this is to set `kgain_params=None` and later in the code, `if kgain_params is None: kgain_params = default`. This is to avoid bugs that can occur when setting python objects (which are mutable) as default arguments.

2025-02-12 23:48 UTC, semaphoreP commented on corgidrp/calibrate_nonlin.py
> +                     verbose=False, nonlin_params=nonlin_params_default):
same comment here as kgain params

2025-02-14 14:36 UTC, kjl0025 commented on corgidrp/walker.py
> +            if image.ext_hdr['ISPC'] and image.pri_hdr['VISTYPE'] != "DARK":
I did it that way b/c I wasn't sure what the 'VISTYPE' would be for PC images, but I suppose it wouldn't be any of the ones checked above this line, so I can put in this inside the `else` statement above it and take out the 'DARK' check.  

And I saw Julia's message about how she would make an issue about CMDGAIN and KGAIN.

2025-02-14 15:39 UTC, semaphoreP reviewed
Sorry to keep dragging this out, but I want to make sure our logic on the walker has no gaps, to avoid bugs in the future.

2025-02-14 15:39 UTC, semaphoreP commented on corgidrp/walker.py
> +                if image.ext_hdr['ISPC']:
can this be done as `if 'ISPC' in image.ext_hdr & image.ext_hdr['ISPC']`? The second have of the conditional will only be run if the first half is True. 

Right now, if "ISPC" is in the header and it is False, the walker does nothing, which is not what we want (I assume we just want it to run "l1_to_2b.json". Same later on below.

2025-02-14 15:39 UTC, semaphoreP commented on corgidrp/walker.py
> +                elif len(unique_vals) == 1: # traditional darks
We shouldn't end on an `if`. We should turn this into an `else` or have an `else` below that raises an Exception. 

Same for the 3 other places you have this structure.

2025-02-14 21:56 UTC, semaphoreP approved these changes
Looks good!

2025-02-14 21:56 UTC, merged